theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo-studio-la-rucette.png'
    footer: '/assets/images/logo-studio-la-rucette-blanc.png'
  home:
    head:
      title: site